### ISSUE TITLE
scan-action is not using the .grype.yaml in repository root

### ISSUE THREAD

**Issue by HarvDrivenDevelopment** [anchore/scan-action#132]
When using the anchore acan-action, I have not been able to get my .grype.yaml file read from anywhere. I have tried repository root, home (~), and directory containing image to scan.

When inputting `debug: true` to the action, I can see grype is invoked with -vv flag, but no additional output is shown other than the error for failed vulnerability check. Example below:

`Executing: grype -vv -o json --fail-on medium docker-image/image.tar
Error: Failed minimum severity level. Found vulnerabilities with level medium or higher`

Upon discussion with @wagoodman , he stated `we're capturing stdout but stderr isn't being captured nor does it inherit that from the parent process (and logging output goes to stderr).`

Hope this helps, thanks

**Comment by luhring** [comment]
Thanks for surfacing this @HarvDrivenDevelopment! We'll have a look.

**Comment by wagoodman** [comment]
Note: when using `-vv` the path to the used configuration is shown 

Expected behavior when fixed:
- When using `debug: true` (in the scan-action workflow yaml) we should be able to see grype is using the config via `configPathUsed` when running the scan-action (in the github actions run output log)
- Scan action should use `.grype.yaml` config files in the root of a repo without any user input/configuration on the scan-action
