### ISSUE TITLE
Allow list for CVE's

### ISSUE THREAD

**Issue by gautampachnandahmo** [anchore/scan-action#84]
I can't currently see a mechanism of whitelist CVE's. Is this currently supported or planned. 

This is specifically use full for failing the build but ignoring one's we dont have a solution for yet.

**Comment by alfredodeza** [comment]
@gautampachnandahmo that is a good question... we don't have any support for this yet, although conversations about allow/deny in `grype` specifically these issues:

https://github.com/anchore/grype/issues/198
https://github.com/anchore/grype/issues/197

However, i believe scan-action could try and accommodate since `grype` hasn't implemented these yet

**Comment by kzantow** [comment]
@gautampachnandahmo we just released an update with `v3` that includes Grype `0.22.0` which now supports ignore lists. You'd need to add a `.grype.yaml` in your repository and [follow the instructions here](https://github.com/anchore/grype#specifying-matches-to-ignore). 🎉
