### ISSUE TITLE
Support Windows Containers

### ISSUE THREAD

**Issue by PartTimeLegend** [anchore/scan-action#95]
Is there any plan to support Windows containers? Currently I can only build a Windows container on a Windows agent and Anchore fails to run on Windows.

**Comment by PartTimeLegend** [comment]
Disappointing that you're not looking to help add security to Windows containers. Thank you for responding.

**Comment by luhring** [comment]
>There is no support for Windows containers

@alfredodeza Does the repo say this somewhere? This is a reasonable curiosity, and I couldn't find that addressed in the README

**Comment by alfredodeza** [comment]
@PartTimeLegend I don't think I explained this well. It isn't that we are not looking to help add security to Windows containers. In fact, Anchore does have support for this in its Enterprise version, which the Open Source variant doesn't support.

If at some point any of this changes for the OSS variant, I'll make sure it is well advertised.

**Comment by alfredodeza** [comment]
> @alfredodeza Does the repo say this somewhere? This is a reasonable curiosity, and I couldn't find that addressed in the README

Good point @luhring, I believe that what _is supported_ is spelled out: 

> By default, a scan will produce very detailed output on system packages like an RPM or DEB, but also language-based packages. These are some of the supported packages and libraries:
> 
> Supported Linux Distributions:
> 
> * Alpine
> * BusyBox
> * CentOS and RedHat
> * Debian and Debian-based distros like Ubuntu

We don't explicitly call out what this tool _does not support_, because it seems that has potential for a wild list (Solaris? BSD? Plan 9? Julia?).

I'm happy to address this as a _separate_ issue if you feel strongly about the README content though, doesn't look useful to keep the conversation going in this ticket which is already closed.

**Comment by luhring** [comment]
@alfredodeza Thanks, that sounds good. Let's open a new ticket and reference this one. I'm guessing we'll get this question again.
